# Generated by Django 3.0.3 on 2021-10-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('description', models.TextField()),
                ('mode', models.CharField(max_length=255)),
                ('celltype', models.CharField(max_length=255, null=True)),
                ('components', models.CharField(max_length=255, null=True)),
                ('doi', models.CharField(max_length=255)),
                ('organism', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('imagefield', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('n_answer', models.IntegerField()),
                ('n_image', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biologicalquizapp.Question')),
            ],
        ),
    ]
