# Generated by Django 3.0.3 on 2021-10-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologicalquizapp', '0002_auto_20211027_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.IntegerField(),
        ),
    ]
